export const intros = [
  "Heeeeyyyyyyooooooooooooo!!",
  "DING DING DING!",
  "BEEP BEEP BEEP!",
  "HOLY MOLY!",
  "FOO-ALERT!",
  "BZZZZT! BZZZZT!",
  "WHOOOOOOSH!",
  "PING! PONG! REMINDER!",
  "SURPRISE! SURPRISE!",
  "SURPRISE! It's reminder time!",
  "PLOT TWIST!",
  "BREAKING NEWS! from the past!",
  "BLAST FROM THE PAST!",
  "FROM THE DEPTHS OF MEMORY!",
  "URGENT UPDATE from Memory HQ!",
  "ATTENTION HUMAN!",
  "INCOMING TRANSMISSION!",
  "RED ALERT! RED ALERT!",
  "Greetings, forgetful earthling!",
  "Your digital memory buddy reporting for duty!",
  "Memory rescue mission activated!",
  "Brain backup system engaged!",
  "Friendly neighborhood reminder here!",
  "Your personal memory coordinator calling!",
  "Don't shoot the messenger, but...",
  "Your brain asked me to tell you...",
  "Plot twist: You actually scheduled this!",
  "Awkward reminder incoming...",
];
